function Topbar({ activePage, onAddTender }) {
  const pageTitles = {
    dashboard: {
      title: 'Investigation Overview',
      description: 'Monitor procurement activity and prioritize cases requiring attention.',
    },
    investigations: {
      title: 'Investigations',
      description: 'Review and prioritize cases generated by procurement signals.',
    },
    tenders: {
      title: 'Tenders',
      description: 'Explore analyzed procurement activity and tender records.',
    },
    vendors: {
      title: 'Vendors',
      description: 'Review vendor activity and procurement relationships.',
    },
    network: {
      title: 'Relationship Network',
      description: 'Explore connections between vendors, tenders and departments.',
    },
    evidence: {
      title: 'Evidence Repository',
      description: 'Trace signals back to the underlying procurement evidence.',
    },
  }

  const current = pageTitles[activePage] || pageTitles.dashboard

  return (
    <header className="topbar">
      <div className="topbar-heading">
        <div className="breadcrumb">
          VIGILANT <span>/</span> {activePage.toUpperCase()}
        </div>

        <h1>{current.title}</h1>

        <p>{current.description}</p>
      </div>

      <div className="topbar-actions">
        <div className="system-time">
          <span className="live-dot" />
          LIVE MONITORING
        </div>

        
      </div>
    </header>
  )
}

export default Topbar

